// Evidence-backed Wave-2 role matrix (canonical workforce ↔ runtime).

export const WAVE2_ROLE_MATRIX = [
  {
    role: "Delivery Product Owner",
    canonicalWorkforceId: "product.delivery-owner",
    department: "product",
    level: "L5",
    responsibility: "Product objective, requirements, acceptance criteria, scope",
    alreadyImplemented: false,
    neededInWave2: true,
    runtimeSlug: "delivery-product",
    reportsTo: "executive-cpo / mianx.cpo.v1",
    dependencies: ["wave-1 executive-cpo"],
  },
  {
    role: "Delivery Architect",
    canonicalWorkforceId: "engineering.senior-backend",
    department: "engineering",
    level: "L5",
    responsibility: "Technical architecture plan for approved specs",
    alreadyImplemented: true,
    neededInWave2: true,
    runtimeSlug: "delivery-architect",
    reportsTo: "executive-cto / mianx.cto.v1",
    dependencies: ["delivery-product"],
  },
  {
    role: "Delivery Engineer",
    canonicalWorkforceId: "engineering.backend",
    department: "engineering",
    level: "L5",
    responsibility: "Work packages + structured implementation results (no repo writes)",
    alreadyImplemented: true,
    neededInWave2: true,
    runtimeSlug: "delivery-engineer",
    reportsTo: "executive-cto / mianx.cto.v1",
    dependencies: ["delivery-architect"],
  },
  {
    role: "Delivery Engineering Reviewer",
    canonicalWorkforceId: "engineering.senior-backend",
    department: "engineering",
    level: "L5",
    responsibility: "Peer review before independent QA; no Founder approval records",
    alreadyImplemented: true,
    neededInWave2: true,
    runtimeSlug: "delivery-review",
    reportsTo: "executive-cto / mianx.cto.v1",
    dependencies: ["delivery-engineer"],
  },
  {
    role: "Delivery Release QA",
    canonicalWorkforceId: "qa.release-verifier",
    department: "qa",
    level: "L5",
    responsibility: "Independent final quality + delivery readiness evidence",
    alreadyImplemented: false,
    neededInWave2: true,
    runtimeSlug: "delivery-qa",
    reportsTo: "executive-cto / mianx.cto.v1",
    dependencies: ["delivery-review"],
    notes:
      "FINAL independent QA owner. Engineering-embedded QA cannot waive this gate.",
  },
  {
    role: "QA Review (Wave-0 runtime)",
    canonicalWorkforceId: "runtime.qa-review",
    department: "qa",
    level: "L5",
    responsibility: "Lead-qualification / product-planning QA verdicts",
    alreadyImplemented: true,
    neededInWave2: false,
    runtimeSlug: "qa-review",
    reportsTo: "mianx.cto.v1",
    dependencies: ["wave-0"],
    notes: "Retained for Wave-0 workflows; not the Wave-2 delivery gate.",
  },
  {
    role: "Engineering-embedded Senior QA",
    canonicalWorkforceId: "engineering.senior-qa",
    department: "engineering",
    level: "L5",
    responsibility: "Embedded test engineering support",
    alreadyImplemented: true,
    neededInWave2: false,
    runtimeSlug: null,
    reportsTo: "mianx.cto.v1",
    dependencies: [],
    notes: "Must NOT own final release certification (separation of duties).",
  },
];

export function wave2ActivatedRuntimeSlugs() {
  return WAVE2_ROLE_MATRIX.filter((r) => r.neededInWave2 && r.runtimeSlug).map(
    (r) => r.runtimeSlug
  );
}
