// Responsibility matrix for Wave-1 Executive / C-Suite control plane.

export const RESPONSIBILITY_MATRIX = [
  {
    slug: "founder",
    level: "L0",
    owns: ["constitutional_authority", "protected_production_decisions", "executive_activation"],
    mayDelegateTo: ["executive-ceo via workflow API"],
    mayRequestApproval: [],
    neverSelfApprove: true,
    founderRequired: [
      "production_deploy",
      "production_destructive_mutation",
      "billing_change",
      "secret_change",
      "permission_ownership_change",
      "legal_commitment",
      "financial_transfer",
      "irreversible_production_action",
      "send_protected_communication",
      "launch_industry_os",
      "disable_security_control",
      "approve_production_action",
      "send_email",
    ],
  },
  {
    slug: "executive-ceo",
    level: "L1",
    owns: ["executive_orchestration", "workstream_planning", "result_aggregation"],
    mayDelegateTo: [
      "executive-cto",
      "executive-coo",
      "executive-cmo",
      "executive-cfo",
      "executive-chro",
      "executive-cpo",
      "executive-cso",
      "executive-ciso",
      "executive-clo",
      "executive-chief-scientist",
    ],
    mayRequestApproval: ["founder"],
    neverSelfApprove: true,
    founderRequired: ["any_protected_production_action"],
  },
  {
    slug: "executive-cto",
    level: "L2",
    owns: ["technology", "engineering_readiness", "platform"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["production_deploy", "schema_migration_apply"],
  },
  {
    slug: "executive-cpo",
    level: "L2",
    owns: ["product", "launch_readiness_product"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["public_product_commitment"],
  },
  {
    slug: "executive-ciso",
    level: "L2",
    owns: ["security", "cyber_risk"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["disable_security_control", "security_policy_exception"],
  },
  {
    slug: "executive-coo",
    level: "L2",
    owns: ["operations", "continuity"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["production_maintenance_window"],
  },
  {
    slug: "executive-cmo",
    level: "L2",
    owns: ["marketing", "growth"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["external_publish", "paid_media_spend"],
  },
  {
    slug: "executive-cfo",
    level: "L2",
    owns: ["finance", "budget_recommendations"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["financial_transfer", "billing_change"],
  },
  {
    slug: "executive-chro",
    level: "L2",
    owns: ["people", "workforce_capacity_recommendations"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["workforce_expansion_spend"],
  },
  {
    slug: "executive-cso",
    level: "L2",
    owns: ["commercial", "sales_readiness"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["contract_commitment"],
  },
  {
    slug: "executive-clo",
    level: "L2",
    owns: ["legal", "compliance_recommendations"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["legal_commitment"],
  },
  {
    slug: "executive-chief-scientist",
    level: "L2",
    owns: ["research", "evaluation"],
    mayDelegateTo: [],
    mayRequestApproval: ["executive-ceo", "founder"],
    neverSelfApprove: true,
    founderRequired: ["external_publication"],
  },
];

export function getResponsibility(slug) {
  return RESPONSIBILITY_MATRIX.find((r) => r.slug === slug) || null;
}

export function founderApprovalBoundaries() {
  return RESPONSIBILITY_MATRIX.find((r) => r.slug === "founder").founderRequired;
}
