// Canonical 20-department registry.
// Slot totals MUST sum to PLANNED_ROLE_SLOT_TOTAL (445).
// Source: doc/19-ai-workforce/AGENT-CAPACITY-BASELINE.md §6

import { PLANNED_ROLE_SLOT_TOTAL } from "./constants";

/**
 * @typedef {object} Department
 * @property {string} id
 * @property {string} slug
 * @property {string} name
 * @property {number} plannedRoleSlots
 * @property {string} mission
 * @property {string} directorTitle
 * @property {string|null} reportsToDepartmentSlug  executive domain owner
 * @property {string|null} executiveAgentSlug       L1/L2 agent that owns the dept
 * @property {string[]} teams
 * @property {string[]} inputs
 * @property {string[]} outputs
 * @property {string[]} upstreamDepartments
 * @property {string[]} downstreamDepartments
 * @property {string[]} kpis
 * @property {string[]} humanApprovalBoundaries
 * @property {string[]} dataAccessBoundaries
 * @property {"named"|"partial"|"capacity_only"} inventoryCompleteness
 */

/** @type {Department[]} */
export const DEPARTMENTS = [
  {
    id: "dept.leadership",
    slug: "leadership",
    name: "Leadership",
    plannedRoleSlots: 11,
    mission:
      "Executive coordination of the MianX AI Operating System under Founder (L0) authority.",
    directorTitle: "AI CEO",
    reportsToDepartmentSlug: null,
    executiveAgentSlug: "mianx.ceo.v1",
    teams: ["executive-office", "strategy"],
    inputs: ["founder_directives", "enterprise_metrics", "risk_escalations"],
    outputs: ["strategy", "executive_decisions", "escalations_to_founder"],
    upstreamDepartments: [],
    downstreamDepartments: [
      "engineering",
      "devops",
      "security",
      "infrastructure",
      "data-ai",
      "product",
      "design",
      "marketing",
      "seo",
      "sales",
      "finance",
      "hr",
      "legal",
      "operations",
      "support",
      "customer-success",
      "research",
      "qa",
      "analytics",
    ],
    kpis: ["strategy_alignment", "escalation_sla", "governance_compliance"],
    humanApprovalBoundaries: [
      "constitutional_changes",
      "executive_activation",
      "production_deploy",
      "billing_and_spend",
    ],
    dataAccessBoundaries: ["enterprise_read_with_audit", "no_secret_exfiltration"],
    inventoryCompleteness: "named",
  },
  {
    id: "dept.engineering",
    slug: "engineering",
    name: "Engineering",
    plannedRoleSlots: 78,
    mission: "Design and build MianX Core and Powered-by-MianX products.",
    directorTitle: "VP Engineering",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cto.v1",
    teams: ["backend", "frontend", "mobile", "ai-ml", "engineering-qa"],
    inputs: ["product_requirements", "architecture_decisions", "security_policy"],
    outputs: ["code", "technical_designs", "engineering_plans"],
    upstreamDepartments: ["product", "design", "research"],
    downstreamDepartments: ["qa", "devops", "infrastructure"],
    kpis: ["delivery_predictability", "defect_escape_rate", "cycle_time"],
    humanApprovalBoundaries: ["production_merge_to_main", "schema_migrations"],
    dataAccessBoundaries: ["project_scoped_source", "no_production_data_without_gate"],
    inventoryCompleteness: "named",
  },
  {
    id: "dept.devops",
    slug: "devops",
    name: "DevOps",
    plannedRoleSlots: 24,
    mission: "Reliability, platforms, and delivery automation.",
    directorTitle: "DevOps Director",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cto.v1",
    teams: ["sre", "platform", "automation"],
    inputs: ["release_candidates", "incident_signals", "infra_requests"],
    outputs: ["pipelines", "runbooks", "reliability_reports"],
    upstreamDepartments: ["engineering", "infrastructure"],
    downstreamDepartments: ["operations", "support"],
    kpis: ["deploy_frequency", "mttr", "change_fail_rate"],
    humanApprovalBoundaries: ["production_deploy", "infra_destroy"],
    dataAccessBoundaries: ["ops_telemetry", "secrets_forbidden_in_prompts"],
    inventoryCompleteness: "named",
  },
  {
    id: "dept.security",
    slug: "security",
    name: "Security",
    plannedRoleSlots: 25,
    mission: "Protect identity, data, and systems; govern cyber risk.",
    directorTitle: "CISO",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.ciso.v1",
    teams: ["security-architecture", "red-team", "compliance-audit"],
    inputs: ["threat_intel", "change_requests", "audit_findings"],
    outputs: ["security_reviews", "policies", "incident_response"],
    upstreamDepartments: ["engineering", "infrastructure", "legal"],
    downstreamDepartments: ["devops", "operations"],
    kpis: ["time_to_detect", "time_to_contain", "control_coverage"],
    humanApprovalBoundaries: [
      "exception_to_security_policy",
      "production_access_elevation",
    ],
    dataAccessBoundaries: ["security_sensitive_with_audit", "secrets_forbidden"],
    inventoryCompleteness: "named",
  },
  {
    id: "dept.infrastructure",
    slug: "infrastructure",
    name: "Infrastructure",
    plannedRoleSlots: 34,
    mission: "Cloud, networking, and platform foundations.",
    directorTitle: "Infrastructure Director",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cto.v1",
    teams: ["cloud", "networking", "capacity"],
    inputs: ["capacity_plans", "architecture_requirements"],
    outputs: ["landing_zones", "network_designs", "capacity_reports"],
    upstreamDepartments: ["engineering", "security"],
    downstreamDepartments: ["devops", "data-ai"],
    kpis: ["availability", "cost_efficiency", "provisioning_lead_time"],
    humanApprovalBoundaries: ["production_network_changes", "account_creation"],
    dataAccessBoundaries: ["infra_config", "secrets_via_vault_only"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.data-ai",
    slug: "data-ai",
    name: "Data & AI",
    plannedRoleSlots: 31,
    mission: "Governed data platforms and AI model operations.",
    directorTitle: "Chief Data Officer",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cto.v1",
    teams: ["data-platform", "ml-ops", "ai-governance"],
    inputs: ["data_products_requests", "model_evaluation_results"],
    outputs: ["datasets", "feature_stores", "model_routes"],
    upstreamDepartments: ["engineering", "research", "analytics"],
    downstreamDepartments: ["product", "operations"],
    kpis: ["data_quality", "model_eval_pass_rate", "lineage_coverage"],
    humanApprovalBoundaries: ["model_allowlist_change", "pii_pipeline_enable"],
    dataAccessBoundaries: ["classified_by_data_class", "no_cross_tenant_bleed"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.product",
    slug: "product",
    name: "Product",
    plannedRoleSlots: 11,
    mission: "Product strategy, discovery, and outcome ownership.",
    directorTitle: "CPO",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cpo.v1",
    teams: ["product-management", "discovery"],
    inputs: ["market_signals", "customer_feedback", "strategy"],
    outputs: ["roadmaps", "requirements", "outcome_metrics"],
    upstreamDepartments: ["research", "sales", "customer-success"],
    downstreamDepartments: ["engineering", "design", "qa"],
    kpis: ["outcome_delivery", "discovery_throughput", "roadmap_confidence"],
    humanApprovalBoundaries: ["public_commitment", "pricing_change"],
    dataAccessBoundaries: ["project_scoped_product_data"],
    inventoryCompleteness: "partial",
  },
  {
    id: "dept.design",
    slug: "design",
    name: "Design",
    plannedRoleSlots: 15,
    mission: "Experience, brand systems, and interaction design.",
    directorTitle: "Design Director",
    reportsToDepartmentSlug: "product",
    executiveAgentSlug: "mianx.cpo.v1",
    teams: ["product-design", "brand", "design-systems"],
    inputs: ["product_briefs", "brand_guidelines"],
    outputs: ["designs", "prototypes", "design_tokens"],
    upstreamDepartments: ["product", "marketing"],
    downstreamDepartments: ["engineering", "qa"],
    kpis: ["design_system_adoption", "usability_issue_rate"],
    humanApprovalBoundaries: ["public_brand_change"],
    dataAccessBoundaries: ["project_scoped_assets"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.marketing",
    slug: "marketing",
    name: "Marketing",
    plannedRoleSlots: 19,
    mission: "Demand, brand, and growth messaging.",
    directorTitle: "CMO",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cmo.v1",
    teams: ["brand", "demand-gen", "content"],
    inputs: ["product_positioning", "audience_insights"],
    outputs: ["campaigns", "content", "growth_experiments"],
    upstreamDepartments: ["product", "sales"],
    downstreamDepartments: ["seo", "sales", "customer-success"],
    kpis: ["pipeline_influence", "brand_consistency"],
    humanApprovalBoundaries: ["external_publish", "paid_media_spend"],
    dataAccessBoundaries: ["marketing_analytics", "no_raw_secrets"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.seo",
    slug: "seo",
    name: "SEO",
    plannedRoleSlots: 14,
    mission: "Organic discovery and search quality.",
    directorTitle: "SEO Director",
    reportsToDepartmentSlug: "marketing",
    executiveAgentSlug: "mianx.cmo.v1",
    teams: ["technical-seo", "content-seo"],
    inputs: ["site_inventory", "search_performance"],
    outputs: ["seo_recommendations", "content_briefs"],
    upstreamDepartments: ["marketing", "product", "engineering"],
    downstreamDepartments: ["marketing", "content"],
    kpis: ["organic_growth", "technical_seo_health"],
    humanApprovalBoundaries: ["sitewide_seo_migration"],
    dataAccessBoundaries: ["public_web_analytics"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.sales",
    slug: "sales",
    name: "Sales",
    plannedRoleSlots: 20,
    mission: "Revenue pipeline and commercial conversations.",
    directorTitle: "CSO",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cso.v1",
    teams: ["pipeline", "partnerships", "revenue-ops"],
    inputs: ["qualified_leads", "product_packaging"],
    outputs: ["opportunities", "forecasts", "deal_notes"],
    upstreamDepartments: ["marketing", "product"],
    downstreamDepartments: ["customer-success", "finance", "legal"],
    kpis: ["pipeline_coverage", "win_rate", "cycle_length"],
    humanApprovalBoundaries: ["contract_commitment", "discount_beyond_policy"],
    dataAccessBoundaries: ["crm_project_scoped"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.finance",
    slug: "finance",
    name: "Finance",
    plannedRoleSlots: 23,
    mission: "Budgets, controls, and financial risk.",
    directorTitle: "CFO",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cfo.v1",
    teams: ["fpna", "controls", "billing"],
    inputs: ["spend_requests", "revenue_actuals"],
    outputs: ["budgets", "forecasts", "control_reports"],
    upstreamDepartments: ["operations", "sales"],
    downstreamDepartments: ["leadership", "legal"],
    kpis: ["budget_variance", "control_exceptions"],
    humanApprovalBoundaries: ["fund_transfer", "billing_change", "vendor_commit"],
    dataAccessBoundaries: ["finance_sensitive", "secrets_forbidden"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.hr",
    slug: "hr",
    name: "Human Resources",
    plannedRoleSlots: 21,
    mission: "AI workforce lifecycle, capability, and org design.",
    directorTitle: "CHRO",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.chro.v1",
    teams: ["workforce-ops", "capability", "org-design"],
    inputs: ["capacity_requests", "performance_signals"],
    outputs: ["role_policies", "activation_recommendations"],
    upstreamDepartments: ["leadership", "operations"],
    downstreamDepartments: ["all_departments_capacity"],
    kpis: ["role_fill_quality", "activation_compliance"],
    humanApprovalBoundaries: ["workforce_expansion_spend", "role_authority_change"],
    dataAccessBoundaries: ["workforce_metadata", "no_personal_secrets"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.legal",
    slug: "legal",
    name: "Legal",
    plannedRoleSlots: 25,
    mission: "Legal, privacy, contracts, and ethics boundaries.",
    directorTitle: "CLO",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.clo.v1",
    teams: ["contracts", "privacy", "ethics"],
    inputs: ["contract_drafts", "policy_questions"],
    outputs: ["legal_opinions", "redlines", "compliance_notes"],
    upstreamDepartments: ["sales", "product", "security"],
    downstreamDepartments: ["leadership", "operations"],
    kpis: ["review_sla", "policy_exception_rate"],
    humanApprovalBoundaries: ["legal_commitment", "privacy_policy_publish"],
    dataAccessBoundaries: ["legal_privileged", "secrets_forbidden"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.operations",
    slug: "operations",
    name: "Operations",
    plannedRoleSlots: 16,
    mission: "Service delivery, continuity, and operating cadence.",
    directorTitle: "COO",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.coo.v1",
    teams: ["service-delivery", "continuity"],
    inputs: ["incident_queues", "delivery_plans"],
    outputs: ["ops_reports", "continuity_plans"],
    upstreamDepartments: ["devops", "support", "engineering"],
    downstreamDepartments: ["support", "customer-success", "leadership"],
    kpis: ["service_availability", "ops_sla"],
    humanApprovalBoundaries: ["production_maintenance_window"],
    dataAccessBoundaries: ["ops_telemetry_project_scoped"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.support",
    slug: "support",
    name: "Support",
    plannedRoleSlots: 18,
    mission: "Customer and operator support response.",
    directorTitle: "Support Director",
    reportsToDepartmentSlug: "operations",
    executiveAgentSlug: "mianx.coo.v1",
    teams: ["tier1", "tier2", "escalations"],
    inputs: ["tickets", "knowledge_base"],
    outputs: ["resolutions", "escalations", "kb_updates"],
    upstreamDepartments: ["customer-success", "product"],
    downstreamDepartments: ["engineering", "qa"],
    kpis: ["first_response_time", "csat"],
    humanApprovalBoundaries: ["goodwill_credit", "data_export_to_customer"],
    dataAccessBoundaries: ["ticket_project_scoped"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.customer-success",
    slug: "customer-success",
    name: "Customer Success",
    plannedRoleSlots: 14,
    mission: "Adoption, retention, and customer outcomes.",
    directorTitle: "Customer Success Director",
    reportsToDepartmentSlug: "operations",
    executiveAgentSlug: "mianx.coo.v1",
    teams: ["onboarding", "retention"],
    inputs: ["account_health", "product_usage"],
    outputs: ["success_plans", "renewal_risk"],
    upstreamDepartments: ["sales", "product"],
    downstreamDepartments: ["support", "product"],
    kpis: ["retention", "expansion", "time_to_value"],
    humanApprovalBoundaries: ["contractual_success_commitment"],
    dataAccessBoundaries: ["account_project_scoped"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.research",
    slug: "research",
    name: "Research",
    plannedRoleSlots: 12,
    mission: "Research, evaluation, and technology transfer.",
    directorTitle: "Chief Scientist",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.chief-scientist.v1",
    teams: ["applied-research", "evaluation"],
    inputs: ["research_questions", "experiment_results"],
    outputs: ["findings", "eval_reports", "transfer_notes"],
    upstreamDepartments: ["product", "data-ai"],
    downstreamDepartments: ["engineering", "product"],
    kpis: ["eval_coverage", "transfer_adoption"],
    humanApprovalBoundaries: ["external_publication"],
    dataAccessBoundaries: ["research_sandbox", "no_production_mutation"],
    inventoryCompleteness: "capacity_only",
  },
  {
    id: "dept.qa",
    slug: "qa",
    name: "Quality Assurance",
    plannedRoleSlots: 18,
    mission: "Independent quality gates for releases and agent outputs.",
    directorTitle: "QA Director",
    reportsToDepartmentSlug: "leadership",
    executiveAgentSlug: "mianx.cto.v1",
    teams: ["product-qa", "agent-qa", "release-qa"],
    inputs: ["build_artifacts", "acceptance_criteria", "agent_outputs"],
    outputs: ["verdicts", "defect_reports", "release_gates"],
    upstreamDepartments: ["engineering", "product"],
    downstreamDepartments: ["devops", "operations"],
    kpis: ["escape_defects", "gate_reliability"],
    humanApprovalBoundaries: ["waive_release_gate"],
    dataAccessBoundaries: ["test_fixtures", "no_self_approve_production"],
    inventoryCompleteness: "partial",
  },
  {
    id: "dept.analytics",
    slug: "analytics",
    name: "Analytics",
    plannedRoleSlots: 16,
    mission: "Truthful metrics, reporting, and decision support.",
    directorTitle: "Analytics Director",
    reportsToDepartmentSlug: "data-ai",
    executiveAgentSlug: "mianx.cto.v1",
    teams: ["bi", "experimentation", "reporting"],
    inputs: ["event_streams", "business_questions"],
    outputs: ["dashboards", "analyses", "metric_definitions"],
    upstreamDepartments: ["data-ai", "product", "operations"],
    downstreamDepartments: ["leadership", "product", "finance"],
    kpis: ["metric_trust", "time_to_insight"],
    humanApprovalBoundaries: ["public_metric_claim"],
    dataAccessBoundaries: ["aggregated_first", "no_fabricated_metrics"],
    inventoryCompleteness: "capacity_only",
  },
];

export function listDepartments() {
  return DEPARTMENTS.map((d) => ({ ...d, teams: [...d.teams] }));
}

export function getDepartment(slug) {
  return DEPARTMENTS.find((d) => d.slug === slug) || null;
}

export function departmentSlotTotal() {
  return DEPARTMENTS.reduce((sum, d) => sum + d.plannedRoleSlots, 0);
}

export function assertDepartmentSlotTotal() {
  const total = departmentSlotTotal();
  if (total !== PLANNED_ROLE_SLOT_TOTAL) {
    throw new Error(
      `Department slot total ${total} !== declared ${PLANNED_ROLE_SLOT_TOTAL}`
    );
  }
  return total;
}
