export const WAVE3_ROLE_MATRIX = [
  {
    role: "Controlled Coding Executor",
    canonicalWorkforceId: "engineering.backend",
    runtimeSlug: "coding-executor",
    department: "engineering",
    level: "L5",
    responsibility: "Workspace-scoped patch candidates + allowlisted verification",
    reportsTo: "executive-cto",
    wave3Required: true,
    activationType: "project_dedicated",
    dependencies: ["wave-2 engineering work package"],
  },
  {
    role: "Platform Security Reviewer",
    canonicalWorkforceId: "security.engineer",
    runtimeSlug: "platform-security",
    department: "security",
    level: "L5",
    responsibility: "Security assessment of candidate changes",
    reportsTo: "executive-ciso",
    wave3Required: true,
    activationType: "project_dedicated",
    dependencies: ["coding-executor"],
  },
  {
    role: "Platform DevOps Planner",
    canonicalWorkforceId: "devops.cicd",
    runtimeSlug: "platform-devops",
    department: "devops",
    level: "L5",
    responsibility: "CI/CD and deployment/rollback planning",
    reportsTo: "executive-cto",
    wave3Required: true,
    activationType: "project_dedicated",
    dependencies: ["platform-security"],
  },
  {
    role: "Platform Infrastructure Planner",
    canonicalWorkforceId: "infrastructure.planner",
    runtimeSlug: "platform-infra",
    department: "infrastructure",
    level: "L5",
    responsibility: "Environment/runtime readiness (no infra mutation)",
    reportsTo: "executive-cto",
    wave3Required: true,
    activationType: "project_dedicated",
    dependencies: ["platform-devops"],
  },
  {
    role: "Platform Data & AI Governance",
    canonicalWorkforceId: "data-ai.governance",
    runtimeSlug: "platform-data-ai",
    department: "data-ai",
    level: "L5",
    responsibility: "Provider/model/schema/isolation/telemetry checks",
    reportsTo: "executive-cto",
    wave3Required: true,
    activationType: "project_dedicated",
    dependencies: ["platform-infra"],
  },
];
