export const WAVE4_ROLE_MATRIX = [
  {
    role: "Operations Coordinator",
    canonicalWorkforceId: "operations.coordinator",
    runtimeSlug: "ops-coordinator",
    department: "operations",
    level: "L5",
    responsibility: "Ops plan, blockers, SLA signals, incident coordination",
    reportsTo: "executive-coo",
    wave4Required: true,
    activationType: "project_dedicated",
  },
  {
    role: "Support Triage Specialist",
    canonicalWorkforceId: "support.triage",
    runtimeSlug: "support-triage",
    department: "support",
    level: "L5",
    responsibility: "Issue intake, classification, draft responses (no send)",
    reportsTo: "executive-coo",
    wave4Required: true,
    activationType: "project_dedicated",
  },
  {
    role: "Analytics Reporter",
    canonicalWorkforceId: "analytics.reporter",
    runtimeSlug: "analytics-reporter",
    department: "analytics",
    level: "L5",
    responsibility: "Truthful metrics with data_available semantics",
    reportsTo: "executive-cto",
    wave4Required: true,
    activationType: "project_dedicated",
  },
];
